/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class TodoItem {
    constructor() {
        this.id = undefined;
        this.uid = " ";
        this.content = " ";
        this.completed = false;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setUid(uid) {
        this.uid = uid;
    }

    getUid() {
        return this.uid;
    }

    setContent(content) {
        this.content = content;
    }

    getContent() {
        return this.content;
    }

    setCompleted(completed) {
        this.completed = completed;
    }

    getCompleted() {
        return this.completed;
    }
}

TodoItem.className = 'TodoItem';

export {TodoItem}